optica/main/routes.py
from flask import render_template, request, Blueprint

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/index')
def index():
    return render_template("index.html")

optica/personas/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from optica import db, bcrypt
from optica.models import Persona, Rol, Genero, Cuenta, Cliente, Colaborador, Paciente, Prevision
from optica.personas.forms import (RegistrationForm, LoginForm,UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from optica.personas.utils import send_reset_email

personas = Blueprint('personas', __name__)



@personas.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        cuenta = Cuenta(cuenta_email=form.email.data,cuenta_password=hashed_password)
        db.session.add(cuenta)
        db.session.commit()
        last_cuenta = Cuenta.query.order_by(Cuenta.cuenta_id.desc()).first()
        persona = Persona(id=form.rut.data, persona_nombre=form.nombre.data, persona_ap_paterno=form.apellido_p.data, persona_ap_materno=form.apellido_m.data, persona_telefono=form.telefono.data, genero_id = form.genero.data, cuenta_id=last_cuenta.cuenta_id)
        cliente = Cliente(id=form.rut.data)
        db.session.add(cliente)
        db.session.add(persona)
        db.session.commit()
        flash(f'Su cuenta ha sido creada satisfactoriamente', 'success')
        return redirect(url_for('personas.login'))
    return render_template('register.html', form=form)



@personas.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        cuenta = Cuenta.query.filter_by(cuenta_email=form.email.data).first()
        if cuenta:
            user = Persona.query.filter_by(cuenta_id=cuenta.cuenta_id).first()
            if user and bcrypt.check_password_hash(cuenta.cuenta_password, form.password.data):
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                flash(f'Sesión Iniciada correctamente', 'success')
                return redirect(next_page) if next_page else redirect(url_for('main.index'))
            else:
                flash('Inicio de secion fallido. Email y/o contraseña invalida', 'danger')
        else:
            flash('Inicio de secion fallido. Email y/o contraseña invalida', 'danger')
    return render_template('login.html', title='Login', form=form)




@personas.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))





@personas.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    print("ACCOUNT")

    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.persona_nombre = form.nombre.data
        current_user.persona_ap_paterno = form.apellido_p.data
        current_user.persona_ap_materno = form.apellido_m.data
        current_user.id = form.rut.data
        current_user.persona_telefono = form.telefono.data
        current_user.genero_id = form.genero.data
        current_user.email = form.email.data
        db.session.commit()
        flash('¡Tu cuenta ha sido actualizada!', 'success')
        return redirect(url_for('personas.account'))
    elif request.method == 'GET':
        form.nombre.data = current_user.persona_nombre
        form.apellido_p.data = current_user.persona_ap_paterno
        form.apellido_m.data = current_user.persona_ap_materno
        form.rut.data = current_user.id
        form.telefono.data = current_user.persona_telefono
        form.genero.data = current_user.genero_id
        persona=Persona.query.filter_by(id=current_user.id).first()
        cuenta=Cuenta.query.filter_by(cuenta_id=persona.cuenta_id).first()
        form.email.data = cuenta.cuenta_email
    return render_template('account.html', form=form)




@personas.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        cuenta = Cuenta.query.filter_by(cuenta_email=form.email.data).first()
        user = Persona.query.filter_by(cuenta_id=cuenta.cuenta_id).first()
        send_reset_email(user)
        flash('Se ha enviado un correo electrónico con instrucciones para restablecer su contraseña.', 'info')
        return redirect(url_for('personas.login'))
    return render_template('reset_request.html', title='Restablecer Contraseña', form=form)




@personas.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = Persona.verify_reset_token(token)
    if user is None:
        flash('Token inválido o vencido', 'warning')
        return redirect(url_for('personas.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('¡Tu contraseña ha sido actualizada! Ahora puede iniciar sesión', 'success')
        return redirect(url_for('personas.login'))
    return render_template('reset_token.html', title='Restablecer Contraseña', form=form)

optica/templates/account.html
{% extends "layout.html" %}
{% block title %}Cuenta{% endblock %}
{% block main %}
<!-- Hero Area Start-->
<div class="slider-area">
  <div class="single-slider slider-height2 d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Cuenta</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Hero Area End-->
<section class="login_part section_padding">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6 mx-auto">

        <div class="col-xl-12">
          {% block mensaje %}
          {{ super() }}
          {% endblock %}
        </div>
<h1>{{ current_user.persona_nombre }} {{current_user.persona_ap_paterno }} {{current_user.persona_ap_materno }}</h1>
<div class="login_part_form border rounded">
  <div class="login_part_form_iner">
    <h3>
      Informacion De Mi Cuenta
    </h3>
    <form class="row contact_form" action="" method="post" novalidate="novalidate">
      {{ form.hidden_tag() }}
      <div class="col-md-6 form-group p_star">

        {% if form.nombre.errors %}
        {{ form.nombre(class="form-control is-invalid", placeholder="Nombre") }}
        <div class="invalid-feedback">
          {% for error in form.nombre.errors %}
          <span class="bg-dark">{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.nombre(class="form-control", placeholder="Nombre") }}
        {% endif %}

      </div>
      <div class="col-md-6 form-group p_star">

        {% if form.apellido_p.errors %}
        {{ form.apellido_p(class="form-control is-invalid", placeholder="Apellido Paterno") }}
        <div class="invalid-feedback">
          {% for error in form.apellido_p.errors %}
          <span class="bg-dark">{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.apellido_p(class="form-control", placeholder="Apellido Paterno") }}
        {% endif %}

      </div>
      <div class="col-md-6 form-group p_star">

        {% if form.apellido_m.errors %}
        {{ form.apellido_m(class="form-control is-invalid", placeholder="Apellido Materno") }}
        <div class="invalid-feedback">
          {% for error in form.apellido_m.errors %}
          <span class="bg-dark">{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.apellido_m(class="form-control", placeholder="Apellido Materno") }}
        {% endif %}

      </div>
      <div class="col-md-6 form-group p_star">

        {% if form.rut.errors %}
        {{ form.rut(class="form-control is-invalid", placeholder="Rut (Ej:11223344-5)") }}
        <div class="invalid-feedback">
          {% for error in form.rut.errors %}
          <span class="bg-dark">{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.rut(class="form-control", placeholder="Rut (Ej:11223344-5)") }}
        {% endif %}

      </div>
      <div class="col-md-12 form-group p_star">

        {% if form.email.errors %}
        {{ form.email(class="form-control is-invalid", placeholder="Email") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span class="bg-dark">{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control", placeholder="Email") }}
        {% endif %}

      </div>
      <div class="col-md-6 form-group p_star">

        {% if form.genero.errors %}
        {{ form.genero(class="form-control is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.genero.errors %}
          <span class="bg-dark">{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.genero(class="form-control", placeholder="Genero") }}
        {% endif %}

      </div>
      <div class="col-md-6 form-group p_star">
        {{ form.telefono(class="form-control", placeholder="Telefono(Opcional)") }}
      </div>

      <div class="col-md-12 form-group">
        <button type="submit" value="submit" class="btn_3">
          Actualizar
        </button>
      </div>
    </form>
  </div>
</div>

      </div>
    </div>
  </div>
</section>

{% endblock %}

optica/templates/layout.html
<!doctype html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{% endblock %} - Optiver</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="manifest" href="site.webmanifest">
  <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">
  <!-- CSS here -->

  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/owl.carousel.min.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/flaticon.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/slicknav.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/animate.min.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/magnific-popup.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/fontawesome-all.min.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/themify-icons.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/slick.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/nice-select.css') }}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css') }}">



</head>

<body>

  <header>
    <!-- Header Start -->
    <div class="header-area">
      <div class="main-header header-sticky">
        <div class="container-fluid">
          <div class="menu-wrapper">
            <!-- Logo -->
            <div class="logo">
              <a href="{{url_for('main.index')}}"><img src="{{url_for('static', filename='images/logo-menu.png') }}"></a>
            </div>
            <!-- Main-menu -->
            <div class="main-menu d-none d-lg-block">
              <nav>
                <ul id="navigation">
                  <li><a href="#">Lentes de sol</a></li>
                  <li><a href="#">Lentes opticos</a></li>
                  <li><a href="#">Lentes de descanso</a></li>
                  <!-- <li class="hot"><a href="#">Accesorios</a> -->
                  <li><a href="#">Accesorios</a>
                    <!-- <ul class="submenu">
<li><a href="shop.html"> MIA</a>
</li>
<li><a href="product_details.html"> Product Details</a></li>
</ul> -->
                  </li>
                </ul>

              </nav>
            </div>
            <!-- Header Right -->
            <div class="header-right">
              <ul>

                <li>
                  {% if current_user.is_authenticated %}
                  <a href="{{url_for('personas.account')}}"><span class="fas fa-cog"></span></a>
                  <a href="{{url_for('personas.logout')}}" data-toggle="tooltip" title="Cerrar Sesión"><span class="fas fa-sign-out-alt"></span>Acceder</a> {% else %}
                  <a href="{{url_for('personas.login')}}" data-toggle="tooltip" title="Iniciar Sesión"><span class="fas fa-user"></span></a> {% endif %}
                </li>

              </ul>
            </div>
          </div>
          <!-- Mobile Menu -->
          <div class="col-12">
            <div class="mobile_menu d-block d-lg-none"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- Header End -->
  </header>


  {% block main %}
      {% block mensaje %}
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  {% for category, message in messages %}
  <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                      {{ message }}
  </div>
                  {% endfor %}
              {% endif %}
          {% endwith %}
      {% endblock %}
  {% endblock %}
  {% block footer %}
  <footer>
    <!-- Footer Start-->
    <div class="footer-area footer-padding">
      <div class="container">
        <div class="row d-flex justify-content-between">
          <div class="col-xl-3 col-lg-3 col-md-5 col-sm-6">
            <div class="single-footer-caption mb-50">
              <div class="single-footer-caption mb-30">
                <!-- logo -->
                <div class="footer-logo">
                  <a href="{{url_for('main.index')}}"><img src="/static/images/logo-menu.png"></a>
                </div>
                <div class="footer-tittle">
                  <div class="footer-pera">
                    <p>Asorem ipsum adipolor sdit amet, consectetur adipisicing elitcf sed do eiusmod tem.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-2 col-lg-3 col-md-3 col-sm-5">
            <div class="single-footer-caption mb-50">
              <div class="footer-tittle">
                <h4>Quick Links</h4>
                <ul>
                  <li><a href="#">About</a></li>
                  <li><a href="#"> Offers & Discounts</a></li>
                  <li><a href="#"> Get Coupon</a></li>
                  <li><a href="#"> Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-md-4 col-sm-7">
            <div class="single-footer-caption mb-50">
              <div class="footer-tittle">
                <h4>New Products</h4>
                <ul>
                  <li><a href="#">Woman Cloth</a></li>
                  <li><a href="#">Fashion Accessories</a></li>
                  <li><a href="#"> Man Accessories</a></li>
                  <li><a href="#"> Rubber made Toys</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-md-5 col-sm-7">
            <div class="single-footer-caption mb-50">
              <div class="footer-tittle">
                <h4>Support</h4>
                <ul>
                  <li><a href="#">Frequently Asked Questions</a></li>
                  <li><a href="#">Terms & Conditions</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">Report a Payment Issue</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!-- Footer bottom -->
        <div class="row align-items-center">
          <div class="col-xl-7 col-lg-8 col-md-7">

          </div>
          <div class="col-xl-5 col-lg-4 col-md-5">
            <div class="footer-copy-right f-right">
              <!-- social -->
              <div class="footer-social">
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="https://www.facebook.com/sai4ull"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-behance"></i></a>
                <a href="#"><i class="fas fa-globe"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Footer End-->
  </footer>
  {% endblock %} {% block js %}
  <!-- JS here -->
  <script src="/static/js/vendor/modernizr.min.js"></script>
  <!-- Jquery, Popper, Bootstrap -->
  <script src="/static/js/vendor/jquery-1.12.4.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap/bootstrap.min.js"></script>
  <!-- Jquery Mobile Menu -->
  <script src="/static/js/jquery.slicknav.min.js"></script>
  <!-- Jquery Slick , Owl-Carousel Plugins -->
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/slick.min.js"></script>
  <!-- One Page, Animated-HeadLin -->
  <script src="/static/js/wow.min.js"></script>
  <script src="/static/js/animated.headline.js"></script>
  <script src="/static/js/jquery.magnific-popup.js"></script>
  <!-- Scrollup, nice-select, sticky -->
  <script src="/static/js/jquery.scrollUp.min.js"></script>
  <script src="/static/js/jquery.nice-select.min.js"></script>
  <script src="/static/js/jquery.sticky.js"></script>
  <!-- contact js -->
  <script src="/static/js/contact.js"></script>
  <script src="/static/js/jquery.form.js"></script>
  <script src="/static/js/jquery.validate.min.js"></script>
  <script src="/static/js/mail-script.js"></script>
  <script src="/static/js/jquery.ajaxchimp.min.js"></script>
  <!-- Jquery Plugins, main Jquery -->
  <script src="/static/js/plugins.js"></script>
  <script src="/static/js/main.js"></script>


  {% endblock %}

</body>

</html>

optica/templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block main %}
<!-- Hero Area Start-->
<div class="slider-area">
  <div class="single-slider slider-height2 d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Login</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Hero Area End-->
<section class="login_part section_padding">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6 mx-auto">

        <div class="col-xl-12">
          {% block mensaje %}
          {{ super() }}
          {% endblock %}
        </div>

        <div class="login_part_form">
          <div class="login_part_form_iner">
            <h3>
              Bienvenido<br />
              Inicie Sesión
            </h3>
            <form class="row contact_form" action="" method="post" novalidate="novalidate">
              {{ form.hidden_tag() }}
              <div class="col-md-12 form-group p_star">
                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid", placeholder="Email") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control", placeholder="Email") }}
                {% endif %}
              </div>
              <div class="col-md-12 form-group p_star">
                {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid", placeholder="Contraseña") }}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control", placeholder="Contraseña") }}
                {% endif %}
              </div>
              <div class="col-md-12 form-group">
                <div class="creat_account d-flex align-items-center">
                  <!-- <input type="checkbox" id="f-option" name="selector" />
                  <label for="f-option">Recuérdame</label> -->
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
                <button type="submit" value="submit" class="btn_3">
                  Iniciar Sesión
                </button>

                <div class="returning_customer">
                  <div class="check_title">
                    ¿Nuevo cliente?
                    <a class="lost_pass" href="{{ url_for('personas.register') }}">Crear una cuenta</a>
                  </div>
                </div>
                <div class="returning_customer">
                  <div class="check_title">
                    <a class="lost_pass" href="{{ url_for('personas.reset_request') }}">¿Olvidaste tu contraseña?</a>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

optica/templates/loginAdmin.html
login colaborador

optica/templates/register.html
{% extends "layout.html" %}
{% block title %}Registro{% endblock %}
{% block main %}
<!-- Hero Area Start-->
<div class="slider-area">
  <div class="single-slider slider-height2 d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Registro</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Hero Area End-->
<section class="login_part section_padding">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6 mx-auto">
        <div class="login_part_text text-center">
          <div class="login_part_form_iner">
            <h2>Registrarse<br /><br /></h2>
            <form class="row contact_form" action="" method="post" novalidate="novalidate">
              {{ form.hidden_tag() }}
              <!-- {{ form.csrf_token }} -->
              <div class="col-md-6 form-group p_star">

                {% if form.nombre.errors %}
                {{ form.nombre(class="form-control is-invalid", placeholder="Nombre") }}
                <div class="invalid-feedback">
                  {% for error in form.nombre.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.nombre(class="form-control", placeholder="Nombre") }}
                {% endif %}

              </div>
              <div class="col-md-6 form-group p_star">

                {% if form.apellido_p.errors %}
                {{ form.apellido_p(class="form-control is-invalid", placeholder="Apellido Paterno") }}
                <div class="invalid-feedback">
                  {% for error in form.apellido_p.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.apellido_p(class="form-control", placeholder="Apellido Paterno") }}
                {% endif %}

              </div>
              <div class="col-md-6 form-group p_star">

                {% if form.apellido_m.errors %}
                {{ form.apellido_m(class="form-control is-invalid", placeholder="Apellido Materno") }}
                <div class="invalid-feedback">
                  {% for error in form.apellido_m.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.apellido_m(class="form-control", placeholder="Apellido Materno") }}
                {% endif %}

              </div>
              <div class="col-md-6 form-group p_star">

                {% if form.rut.errors %}
                {{ form.rut(class="form-control is-invalid", placeholder="Rut (Ej:11223344-5)") }}
                <div class="invalid-feedback">
                  {% for error in form.rut.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.rut(class="form-control", placeholder="Rut (Ej:11223344-5)") }}
                {% endif %}

              </div>
              <div class="col-md-12 form-group p_star">

                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid", placeholder="Email") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control", placeholder="Email") }}
                {% endif %}

              </div>
              <div class="col-md-6 form-group p_star">

                {% if form.genero.errors %}
                {{ form.genero(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.genero.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.genero(class="form-control", placeholder="Genero") }}
                {% endif %}

              </div>
              <div class="col-md-6 form-group p_star">
                {{ form.telefono(class="form-control", placeholder="Telefono(Opcional)") }}
              </div>
              <div class="col-md-6 form-group p_star">

                {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid", placeholder="Contraseña") }}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control", placeholder="Contraseña") }}
                {% endif %}

              </div>
              <div class="col-md-6 form-group p_star">

                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control is-invalid", placeholder="Repetir Contraseña") }}
                <div class="invalid-feedback">
                  {% for error in form.confirm_password.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control", placeholder="Repetir Contraseña") }}
                {% endif %}

              </div>

              <div class="col-md-12 form-group">
                {{ form.submit(class="btn_3") }}
                <!-- <button type="submit" value="submit" class="btn_3">
                                                            Registrarme
                                                        </button> -->
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

optica/templates/reset_request.html
{% extends "layout.html" %}
{% block title %}{% endblock %}
{% block main %}
<!-- Hero Area Start-->
<div class="slider-area">
  <div class="single-slider slider-height2 d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Login</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Hero Area End-->
<section class="login_part section_padding">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6 mx-auto">

        <div class="col-xl-12">
          {% block mensaje %}
          {{ super() }}
          {% endblock %}
        </div>

        <div class="login_part_form">
          <div class="login_part_form_iner">

            <h3 class="mb-2">
              Restablecer contraseña<br /></h3>
            <p>Te enviaremos un correo electrónico para restablecer tu contraseña.</p>


            <form class="row contact_form mt-5" action="" method="post" novalidate="novalidate">
              {{ form.hidden_tag() }}
              <div class="col-md-12 form-group p_star">
                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid", placeholder="Email") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                  <span class="bg-dark">{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control", placeholder="Email") }}
                {% endif %}
              </div>
              <div class="col-md-12 form-group">
                <button type="submit" value="submit" class="btn_3">
                  Enviar
                </button>


              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}